### ISSUE TITLE
let vs const as default, your opinion ?

### ISSUE THREAD

**Issue by itaditya** [sdras/array-explorer#72]
Hi @sdras , I noticed that you're using `let` everywhere for default case, even when no reassignment occurs. Is this intentional ? I thought as default we'd use `const`.

**Comment by anonyco** [comment]
Honestly, there is *zero* advantage to using *let* over *var* if one is using the variable properly because it only changes the scope. Using it properly means explicitly setting objects to null after they are used in circumstances where a timer is used in the same scope to the effect of consoling the browser with, "It's okay, this object is gone and will not be 'eval'ed anymore, so it can truely be freed."

**Comment by itaditya** [comment]
@anonyco I'll know I mastered JavaScript when I'll understand your comment

**Comment by sdras** [comment]
IIRC (It's been a while since I made this), I used `let` because some of the methods mutate and so `const` wouldn't be permitted and I felt it was better to keep things consistent. I could have just let it be `var` I suppose. But that was the reasoning behind it. Open to more discussion about it.
