### ISSUE TITLE
Cloning an array

### ISSUE THREAD

**Issue by ifollowedthewhiterabbit** [sdras/array-explorer#88]
Awesome tool btw, thanks! I have been working up the courage to contribute open source and maybe this could be the start of it. 

I had to recently clone an array for a work project.
I see that you have a feature to do that in the ObjectExplorer. 

Could we look at adding one here too?

**Comment by sdras** [comment]
Hi @ifollowedthewhiterabbit! 

I really want to support you in contributing to open source, however, these explorers literally document Array and Object methods. (See [MDN for details](https://developer.mozilla.org/en-US/)) I would be open to adding a tips section similar to how I deal with the anatomy of an object in the other explorer. Otherwise, I'll try to label some things as "good first issue" that might get you started. Cheers!

**Comment by ifollowedthewhiterabbit** [comment]
Cheers @sdras! 

Im definitely keen to get involved. Thank you for adding the labels :)
